Hw1
shinnik/2018-FS-11-Frontend-Izrailev pull request #1
Opened 2018-10-11 18:50 UTC by shinnik

Pulled first homework (Izrailev)

2018-10-12 11:36 UTC, martinkomitsky requested changes

2018-10-12 11:36 UTC, martinkomitsky commented on dist/main.js
> +!function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||O
Удалить файл и положить в gitignore

2018-10-12 11:36 UTC, martinkomitsky commented
Исправить замечания, запустить линтер и исправить все ошибки, что он говорит

2018-10-14 17:39 UTC, shinnik commented
Мартин, все исправил, вроде!

2018-10-15 09:34 UTC, martinkomitsky approved these changes

2018-10-15 09:34 UTC, merged

2018-10-15 09:34 UTC, martinkomitsky commented
теперь супер, 10