sem2 hw1 is done
shinnik/2018-FS-11-Frontend-Izrailev pull request #11
Opened 2019-03-02 12:58 UTC by shinnik

User can add and send emojis (I added only six or seven emojis for example). Emojis are displayed both in contenteditable field and in messages itself.

NOTE: add any value in access_token field to get access to chats (link in popup menu on header will appear).

2019-03-02 15:45 UTC, martinkomitsky commented
@shinnik а иконки в спрайт не объединял?
https://github.com/mialinx/tt-fullstack/blob/master/2sem/front/lesson-1/homework.md

2019-03-02 16:37 UTC, shinnik commented
@martinkomitsky  объединял css-sprite-loader-ом )

2019-03-02 16:42 UTC, shinnik commented
Там у всех картинок в css проставил в background "...?sprite" в url-е. Он их, вроде, объединил в спрайт всех

2019-03-02 16:55 UTC, shinnik commented
Ааа, я понял, в чем дело, наверное. Там же мне вручную пришлось прописывать в конфиге webpack-а create-react-app этот лоадер. Он лежит в node_modules/react-scripts/config/. Сейчас я его тогда тоже запушу сюда.

2019-03-03 07:08 UTC, martinkomitsky commented
Только эта история работать не будет. Пока cra находится в исходном состоянии - нам недоступны любые манипуляции со скриптами сборки. Сначала надо сделать `npm run eject`, и затем в появившихся конфигах что-то править.

2019-03-03 12:46 UTC, shinnik commented
Все бандлиться, вроде, теперь )

2019-03-05 17:29 UTC, martinkomitsky commented
OK, спрайт есть. Но как мне отправить любой из твоих смайлов?

![2019-03-05 20 29 05](https://user-images.githubusercontent.com/14847018/53824608-6b9a8600-3f85-11e9-9cc3-79f4438fd3c4.png)

При нажатии ничего не происходит.

2019-03-05 19:53 UTC, shinnik commented
@martinkomitsky Он ставит туда, где стоит каретка. Если выставить ее на инпуте не сработает?

2019-03-05 20:05 UTC, shinnik commented
@martinkomitsky Попробуйте, пожалуйста, теперь

2019-03-06 08:54 UTC, martinkomitsky commented
https://cloud.mail.ru/public/L3Rx/UbSWk84Wx
нет. При клике в поле ввода должна появляться либо кодовая строка, либо настоящий emoji

2019-03-06 11:36 UTC, shinnik commented
@martinkomitsky Мне очень сложно пока понять почему оно не работает. У меня вот так выглядит:
https://drive.google.com/file/d/1Gr96AnFcwsUEJWUOt0DJPvJFc_LHTnUL/

2019-03-07 07:33 UTC, shinnik commented
@martinkomitsky, должно работать теперь

2019-03-08 13:36 UTC, martinkomitsky commented
![image](https://user-images.githubusercontent.com/14847018/54031503-fa92e280-41bf-11e9-999c-e8c669e3b314.png)
Работает, действительно. Но Нашел маленькие баги:
* Если написать текст, а потом поставить курсор в какое-то место, то эмоджи всегда вставляются в начало строки
* Емоджи сложно удалить с первого раза.

Если это все поправишь, то поставлю максимум с бонусом

2019-03-08 13:37 UTC, martinkomitsky requested changes
Исправить замечания

2019-03-08 19:01 UTC, shinnik commented
@martinkomitsky вроде бы все должно быть поправлено

2019-03-09 14:04 UTC, martinkomitsky approved these changes

2019-03-09 14:05 UTC, merged

2019-03-09 14:05 UTC, martinkomitsky commented
10 + бонус