Sem2hw6
shinnik/2018-FS-11-Frontend-Izrailev pull request #15
Opened 2019-04-18 10:41 UTC by shinnik

Добавлены два компонента, реализованные с помощью хуков. Контекст уже был ранее использован для проброса шэрдворкера внутрь компонентов. Устаревший метод componentWillMount заменен componentDidMount.

2019-04-19 15:32 UTC, martinkomitsky requested changes
Исправить замечания

2019-04-28 09:57 UTC, martinkomitsky commented
@shinnik а ты это дз поправил? не вижу правок в ветке

2019-04-29 09:30 UTC, merged

2019-04-29 09:33 UTC, shinnik commented
@martinkomitsky я просто не нашел тут комментариев и подумал, что это к другому коммиту относится

2019-04-29 09:39 UTC, martinkomitsky commented
@shinnik а они были. Ты их удалил, что ли?)

2019-04-29 09:40 UTC, martinkomitsky commented
@chexex ???

2019-04-29 09:44 UTC, shinnik commented
@martinkomitsky нет, конечно ) их и не было никогда. Тут сразу появился только самый первый комментарий

2019-04-29 09:46 UTC, martinkomitsky commented
@shinnik какая-то мутная история, я почти на 100% уверен, что видел тут Лешины комментарии. В любом случае, ждем их появления, подтягиваем сюда мастер, исправляем и открываем новый PR)

2019-04-29 11:17 UTC, chexex reviewed
Единственный серьезный вопрос про `componentWillUnmount` -> `componentDidMount`.
Метод `componentWillUnmount` не входит в состав методов, исключенных из поддержки.
https://github.com/reactjs/react-codemod/blob/master/transforms/rename-unsafe-lifecycles.js#L14-L16

2019-04-29 11:17 UTC, chexex commented on src/lib/components/UserAvatar/UserAvatar.js
> +            <img onClick={() => setClicked(!clicked)} alt="noav" src={'https://api.adorable.io/avatars/220/abott@adorable.png'} className={clicked ? classes.avatarSelected : classes.avatar}></img>
Крайне рекомендую разбивать длинные выражения на строки
```js
<img
  onClick={() => setClicked(!clicked)}
  alt="noav"
  src={'https://api.adorable.io/avatars/220/abott@adorable.png'}
  className={clicked ? classes.avatarSelected : classes.avatar}
/>
```

2019-04-29 11:17 UTC, chexex commented on src/lib/containers/Chat/chat.js
>  };
Сокращенная версия :)
```js
const mapStateToProps = state => ({
  chatName: state.ch.name,
  unread: state.ch.numOfMessages,
  chatID: state.ch.chat_id,
})
```

2019-04-29 11:17 UTC, chexex commented on src/lib/containers/Chat/chat.js
> +    componentDidMount() {
Почему здесь было решено так сделать?

2019-05-02 10:43 UTC, shinnik commented on src/lib/containers/Chat/chat.js
>  };
Да, забыл про это, спасибо!

2019-05-02 10:43 UTC, shinnik commented on src/lib/components/UserAvatar/UserAvatar.js
> +            <img onClick={() => setClicked(!clicked)} alt="noav" src={'https://api.adorable.io/avatars/220/abott@adorable.png'} className={clicked ? classes.avatarSelected : classes.avatar}></img>
Разбил )

2019-05-02 10:44 UTC, shinnik commented on src/lib/containers/Chat/chat.js
> +    componentDidMount() {
Перепутал с compnonentWillMount, который deprecated