Sem2hw7
shinnik/2018-FS-11-Frontend-Izrailev pull request #16
Opened 2019-04-18 17:33 UTC by shinnik

Тесты написаны для функции getReadableSize (coverage 100)

2019-04-19 07:19 UTC, martinkomitsky commented on src/lib/components/utils/getReadableSize.js
> +module.exports = getReadableSize;
Круто, а что будет, если передать отрицательное число?))) надо модифицировать код таким образом, чтобы отрицательные значения не высчитывались и тоже выдавался `false` + написать про это тест

2019-04-19 07:22 UTC, martinkomitsky requested changes
Исправить замечания

2019-04-19 07:22 UTC, martinkomitsky commented on src/lib/containers/Keyboard/EmojiKeyboard.js
> +import { EMOJIS } from "./emojis";
Респект за вынесение несвязного кода в отельный модуль!

2019-04-19 07:22 UTC, martinkomitsky commented on package.json
> +    "test": "jest",
А зачем так? стандартный скрипт тестирования круче

2019-04-20 08:04 UTC, shinnik commented
Замечания, вроде бы, исправлены

2019-04-29 09:30 UTC, martinkomitsky approved these changes

2019-04-29 09:30 UTC, merged

2019-04-29 09:30 UTC, martinkomitsky commented
ДЗ7: 10 плюс бонус